### ISSUE TITLE
As a developer, I need to recover from the Ope

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-simulation-runner#57]
## Implementation Tasks
This story will document all the tasks that are still left to complete for the simulation project. Each tasks will have a list of TODOs and some resources that can help you move forward on the project. 

### 1. As a user, I want to be able to select a layout
For this story we need to implement a vertical slice of features that will enable our application to leverage real data when it exists. 

#### Diagram

```mermaid
---
title: Layout Sequence Diagram
---
sequenceDiagram
    autonumber

    actor User
    participant UI as Simulation UI
    participant S_API as Simulation API
    participant L_API as Layouts API or Mock

    User->>+UI: Navigates to http://localhost:9010/
        UI->>+S_API: GET http://localhost:9010/layouts
        S_API->>+L_API: GET http://localhost:9003/layouts
        L_API->>-S_API: Layouts API responds with all layouts
        S_API->>-UI: Simulation API responds with only needed data
        UI-->>UI: Updates state with Layouts 
    UI->>-User: Page is Loaded ready for the user to interact

    User->>+UI: User selects Layout from dropdown
    UI->>-User: Selected layout is displayed in UI
```

#### Tasks
- [x] @blenaneraio UI
  - [x] There is a Settings form with the layout dropdown in the UI
  - [x] @chris-marfia When the page loads the UI calls the API to retrieve all the layout names and IDs to populate the dropdown
  - [x] The layout dropdown can open and select a layout 
- [x] @calisward API
  - [x] There is an API GET endpoint to retrieve all the layout names and their IDs
  - [x] There is an `@Service` that will make an API call to the layouts API to retrieve the data and return it to the UI
- [x] @calisward @AyoAwodeyi  Mock API (since the layouts API does not exist yet)
  - [x] create a `/mocks` folder and have what you need to create a mock API for the layouts
  - [x] Use mocker-api for this (https://www.npmjs.com/package/mocker-api)
  - [x] Don't forget to add a script in the package.json for running the mock
    - `"mock:layouts": "mocker ./mock/layoutapi.js --host localhost --port 9003"`
  - [x] Delete the `mocks` folder in the `src` folder 

If you need an example you can look at the Dashboard team's work here: https://github.com/Access-Point-Program/cohort-3-dashboard

### 2. As a user, I want to be able to select a Ruleset
For this story we need to implement a vertical slice of features that will enable our application to leverage real data when it exists. 

#### Diagram

```mermaid
---
title: RuleSet Sequence Diagram
---
sequenceDiagram
    autonumber

    actor User
    participant UI as Simulation UI
    participant S_API as Simulation API
    participant L_API as RuleSets API or Mock

    User->>+UI: Navigates to http://localhost:9010/
        UI->>+S_API: GET http://localhost:9010/rulesets
        S_API->>+L_API: GET http://localhost:8080/rulesets
        L_API->>-S_API: RuleSets API responds with all RuleSets
        S_API->>-UI: Simulation API responds with only needed data
        UI-->>UI: Updates state with RuleSets 
    UI->>-User: Page is Loaded ready for the user to interact

    User->>+UI: User selects RuleSets from dropdown
    UI->>-User: Selected RuleSets is displayed in UI
```

#### Tasks
- [x] @AyoAwodeyi UI
  - [x] There is a Settings form with the ruleset dropdown in the UI
  - [x] @chris-marfia When the page loads the UI calls the API to retrieve all the ruleset names and IDs to populate the dropdown
  - [x] The ruleset dropdown can open and select a ruleset 
- [x] @kwhitehead23 @GabrielIvey0 API
  - [x] There is an API GET endpoint to retrieve all the ruleset names and their IDs
  - [x] There is an `@Service` that will make an API call to the rulesets API to retrieve the data and return it to the UI
- [x] @calisward @AyoAwodeyi   Mock API (since the rulesets API does not exist yet)
  - [x] create a `/mocks` folder and have what you need to create a mock API for the rulesets
  - [x] Use mocker-api for this (https://www.npmjs.com/package/mocker-api)
  - [x] Don't forget to add a script in the package.json for running the mock
    - `"mock:rulesets": "mocker ./mock/rulesetapi.js --host localhost --port 9003"`
  - [x] Delete the `mocks` folder in the `src` folder 
- [x] #69
  - @GabrielIvey0 @kwhitehead23 @blenaneraio  

If you need an example you can look at the Dashboard team's work here: https://github.com/Access-Point-Program/cohort-3-dashboard

### 3. Validate that the UI runs through the API
The UI application about be able to be accessed from the same port as the API. This happens by running the Spring Boot application and getting access to the UI via http://localhost:9010/. We need to validate that this is working as it should be.

- [x] Need to make sure that when the Spring Boot application is run that the UI will appear on the default home page for the port http://localhost:9010/.

### 4. Implement Redux

- [x] Instructor to walk through and implement Redux with the team on a recorded call. 

### 5. Clean up the code base from React Router
There are many pages and components that still exist from the usage of React Router. These pages and components should be deleted. 

- [x] Clean up the extra pages and references
  - [x] Delete the Dashboard.js file
  - [x] Delete the Reports.js file
  - [x] Delete the Simulation.js file and move the body of that component into the App.js. 

### 6. 
@blenaneraio 
- [x] The Grid and Legend components use inline styles

At the moment, the `Grid` and `Legend` components are using a mix of inline styles and CSS files. The Cohort as a whole agreed to use Bootstrap for the design. I would remove all the inline styles and leverage Bootstrap for everything you can. If there are custom styles that you need. I would make classes and style them in one CSS file.

### 7. Update the SQL generation in the application.properties
Part of the integrate Postgres and Spring Boot story was to make Spring Boot **not** generate any SQL. At the moment, in the application properties the DDL generation is set to create. This should be set to none and the `schema.sql` file should be used for the creation of the database tables. If the schema does not create correctly then that SQL will need to be revisited.
- [x] @kwhitehead23 @jgarner76  Update application.properties
  - [x] DDL generation is set to none
  - [x] Use schema.sql for creation of the database tables
    - [x] Delete all database tables
    - [x] Run schema.sql file inside of pgAdmin4
    - [x] Run application
    - [x] Test that we can interact with the database
- If schema does not create the tables correctly, the SQL will need to be revisited

### 8. All the endpoints for the Spring Boot application should be documented.
Part of the capstone is to document all the API endpoints in Postman. Create a postman collection similar to other teams and start documenting the API. Once all the API endpoints are documented. Export the collection and add it to the GitHub repository. 
 @jgarner76 @calisward 
- [ ]  API endpoints documented in postman
- [ ]  Create postman collection
- [ ]  Export the collection and add it to the github repository

### 9.  

- [ ] @jgarner76  @kwhitehead23 Validate that when you save simulation results they go into the database correct. 

There are endpoints for the Simulation Results. I see ones to retrieve and save the data. These need to be validated that they are actually working. From the understanding on Monday it would not confirmed that they work as of today. 

### 10. 

- [ ] @jgarner76  All API endpoints in the Simulation API need to be unit tested with Rest Assured.

This includes the Simulation Results controller, Layouts controller, RuleSets controllers. We should be testing for the following types of things. 

1. Status code is correct
2. Data is what we expect in the response
3. What happens if in error/exception is thrown.

### 11. 

- [ ] @blenaneraio The UI should have unit tests

As you are developing the features of the UI they should be tested to *prove* that they work as expected. These test should be using Jest and the React Testing Library.

### 12. Sidebar Styles

- [x]  - @blenaneraio 

### 13. Sidebar Links

- [x] - @blenaneraio 

### 14. Use Bootstrap instead of custom CSS 

- [x] - @blenaneraio 

### 15. Missing the Simulation Results move list 

- [ ] - @calisward @blenaneraio 

### 16. Missing the Run Simulation Button

- [x] - @blenaneraio 

### 17. Missing the Max Iterations text box and state management
- [x] - @AyoAwodeyi 
> TODO

### 18. Need to implement the Rules Engine when the simulation 
- [ ] - @calisward 

> TODO
