### ISSUE TITLE
As a user, I need to be able to get a Ruleset by it's ID for running the simulation

### ISSUE THREAD

**Issue by ghost** [Access-Point-Program/cohort-3-simulation-runner#69]
This story is to implement a vertical slice for implementing the get Ruleset by ID. The story will involve the following actions:

#### Diagram

```mermaid
---
title: Layout Sequence Diagram
---
sequenceDiagram
    autonumber

    actor User
    participant UI as Simulation UI
    participant S_API as Simulation API
    participant L_API as Rulesets API or Mock

    User->>+UI: User selects Ruleset from dropdown
        UI->>+S_API: GET http://localhost:9010/rulsets/:ruleset_id
        S_API->>+L_API: GET http://localhost:9003/rulesets/:ruleset_id
        L_API->>-S_API: Rulesets API responds with the Ruleset by it's id
        S_API->>-UI: Simulation API responds with only needed data
        UI-->>UI: The Ruleset is updated in Redux
    UI->>-User: Selected Ruleset is displayed in UI
```

### Tasks

- [x] Create a new @GetMapping in the Ruleset controller for the get RuleSet By ID
- [x] Create a new method in the RulesetsService that will call the Rulesets API or mock by ID
- [x] Create a new models in the model packaged for all the different Ruleset components (RuleSet, Rules, Conditions).
- [x] Update the Ruleset mock in the mocks folder to have a mocked Get endpoint that behaves like the actual Ruleset API
	- [x] This will involve meeting with the Cyclones team and understanding what the API looks like and what it returns. They have a postman collection that they can share with you that has examples.
- [x] Updating the RuleSetController unit tests to test this new endpoint
- [x] Update the newly added RulesetApiSlice in the React application to have a new query that will call this API endpoint.

This will be a new feature that no other team has completed yet. You **WILL** need to meet with the Cyclones team to understand what their API looks like **BEFORE** moving forward on the story. After you understand the story you can use the examples already in your codebase to complete the story. Each one of the TODOs above should be everything that you need to do. Before working on this story you will need to finish reviewing the implement redux PR and merge that to the main branch. This is needed for the last TODO. 

### Resources
- Location of mocks: https://github.com/Access-Point-Program/cohort-3-simulation-runner/blob/main/mocks/rulesets.mock.js
- Location of controller: https://github.com/Access-Point-Program/cohort-3-simulation-runner/blob/main/src/main/java/com/HocusPocus/Simulation/simulationDb/controller/RuleSetsController.java
- Location of models: https://github.com/Access-Point-Program/cohort-3-simulation-runner/tree/main/src/main/java/com/HocusPocus/Simulation/simulationDb/models
- Location of service: https://github.com/Access-Point-Program/cohort-3-simulation-runner/blob/main/src/main/java/com/HocusPocus/Simulation/simulationDb/services/RuleSetsService.java
- Location of tests: https://github.com/Access-Point-Program/cohort-3-simulation-runner/blob/main/src/test/java/com/HocusPocus/Simulation/RuleSetsControllerTests.java
- Location of redux slice: https://github.com/Access-Point-Program/cohort-3-simulation-runner/blob/implement-redux/ui/src/store/ruleSetsSlice.js
- Redux Toolkit quickstart guide: https://redux-toolkit.js.org/tutorials/rtk-query
