### ISSUE TITLE
As a developer, I need to our Spring Application to correctly connect to the database using our database model.

### ISSUE THREAD

**Issue by chris-marfia** [Access-Point-Program/cohort-3-simulation-runner#89]
### Description

Pulled from Story #57 

> 7. Update the SQL generation in the application.properties
Part of the integrate Postgres and Spring Boot story was to make Spring Boot not generate any SQL. At the moment, in the application properties the DDL generation is set to create. This should be set to none and the schema.sql file should be used for the creation of the database tables. If the schema does not create correctly then that SQL will need to be revisited.
>
> - [ ] @kwhitehead23 @jgarner76 Update application.properties
>    - [x] DDL generation is set to none
>    - [ ] Use schema.sql for creation of the database tables
>      - [x] Delete all database tables
>      - [x] Run schema.sql file inside of pgAdmin4
>      - [x] Run application
>      - [ ] Test that we can interact with the database
> - [ ] If schema does not create the tables correctly, the SQL will need to be revisited

## Tasks

- [ ] 1. Correct database model
- [ ] 2. Update the `@Entity` in the Spring Boot application to match the database model
- [ ] 3. Update the application.properties file to not generate anymore SQL.
- [ ] 4. Verify that the application can start, run, and the list and save endpoints for the Simulation Results are correctly saving data to the database.

## Acceptance Criteria
- The `schema.sql` contains everything that is needed for the table structure in the database.
- There is a `roles.sql` file that contains everything needed for permissions in the database
- The `SimulationResults` @Entity correctly maps one-to-one with the database tables
- The **POST** endpoint to save simulation results correctly saves ALL database fields to the database.
- The **GET** endpoint to retrieve simulation results correctly retrieves all simulation results from the database 

### Definition of Ready

- [ ] Need to be properly informed on how to do a story before starting it
- [ ] Make sure that the stories are taken on when you expect that you can complete them
- [ ] Make sure that there are proper materials to complete stories before starting them
- [ ] Need to discuss stories as a group before adding them to the backlog
- [ ] Having a contingency plan
- [ ] Have a game plan on how to complete the story
- [ ] To start a story the team needs to agree that a story has enough detail on what should be done and that it is close enough to the project manager's idea
